export type PlaylistTrack = {
  youtubeId: string;
  title: string;
  artist: string;
};

/** YouTube Music playlist PLRz1AQjOKrFmEpurQigk029b53Y9t_Gaj */
export const NOW_PLAYING = {
  tracks: [
    { youtubeId: "Snyan1_jGWc", title: "사랑하게 될 거야", artist: "한로로 HANRORO" },
    { youtubeId: "x_rftS4F3rY", title: "Last Love (마지막 사랑)", artist: "신예영 SIN YE YOUNG" },
    { youtubeId: "CURhR3evy6Y", title: "Endless", artist: "flower" },
    { youtubeId: "yuH4OnvoADU", title: "Leave Me, Don′t Go", artist: "기태 (순순희) GITAE OFFICIAL" },
    { youtubeId: "3vH4GiEN0p0", title: "까만안경 (FEAT. DAY LIGHT)", artist: "Eru" },
    { youtubeId: "ww_w2AqLIUo", title: "Love You and Hate You (혼자 사랑하고 미워해)", artist: "백예슬 YESEUL" },
    { youtubeId: "CgmGJZjLmes", title: "사랑한 만큼", artist: "Tim" },
    { youtubeId: "I0Hu7PRF4j0", title: "입춘", artist: "한로로 HANRORO" },
    { youtubeId: "VZnfZ14fIig", title: "기억을 걷는 시간", artist: "OFFICIAL_NELL" },
    { youtubeId: "TXp5D0DkzJw", title: "LOVE AGAIN (2025)", artist: "아샤트리 AshaTree" },
    { youtubeId: "82s8PRgYSRU", title: "Daydream", artist: "웬디 WENDY" },
    { youtubeId: "Fyq1xGpg24A", title: "Nothing Between Us (너와 나는 이제 남이니까)", artist: "Sojung" },
    { youtubeId: "H-Ci18cc1js", title: "미인", artist: "Ki Chan Lee" },
    { youtubeId: "MzKOG1vwj2Y", title: "Eternity (흩어지지 않게)", artist: "M.C the MAX Official" },
    { youtubeId: "ZtcM3KhgF-s", title: "Wild Flower (야생화)", artist: "박효신 PARK HYO SHIN" },
    { youtubeId: "UE2FMYtgoyA", title: "Lying On Your Lips (입술의 말)", artist: "M.C the MAX Official" },
    { youtubeId: "E8KQK2hERuk", title: "Bad Love (몹쓸 사랑)", artist: "반하나 BANHANA" },
    { youtubeId: "RqImBZoOmF8", title: "Starting With You ❍", artist: "Park Da Hye" },
    { youtubeId: "gF-MfOdo7L8", title: "To You My Light (feat. LEE RAON)", artist: "마크툽 MAKTUB Official" },
    { youtubeId: "Xc6IHbaxPlU", title: "날 그만 잊어요 (Forget Me Now)", artist: "GUMMY - 거미" },
    { youtubeId: "j6R70cI4bvs", title: "친구라도 될걸 그랬어 (We should have become friends)", artist: "GUMMY - 거미" },
    { youtubeId: "KdKucPl2lXA", title: "Propose", artist: "Hot Potato" },
    { youtubeId: "QNt7KUUk_d8", title: "기다리다", artist: "YOUNHA OFFICIAL" },
    { youtubeId: "j1uXcHwLhHM", title: "Event Horizon (사건의 지평선)", artist: "YOUNHA OFFICIAL" },
    { youtubeId: "sAPNZjPf1sc", title: "빛이 나는 너에게 (Dear My Light)", artist: "DAWN" },
    { youtubeId: "i4Duvh3QLGM", title: "Again", artist: "신예영 SIN YE YOUNG" },
    { youtubeId: "dHikGUDW7B4", title: "Since I knew you (그대를 알고)", artist: "하예일기장" },
    { youtubeId: "hhTk3l9UfW0", title: "I will be your shining star (밝게 빛나는 별이 되어 비춰줄게)", artist: "송이한 Song I Han" },
    { youtubeId: "EAWHtXQpYX4", title: "사랑 안해", artist: "백지영 Baek Z Young" },
    { youtubeId: "44DXUKuX5FY", title: "I still love you a lot", artist: "백지영 Baek Z Young" },
    { youtubeId: "7fHYE8BI9kc", title: "잠시만 안녕", artist: "M.C the MAX Official" },
    { youtubeId: "2WsvXe11Xic", title: "I miss you a lot (네가 보고 싶은 건 자연스러운 거겠지)", artist: "신예영 SIN YE YOUNG" },
    { youtubeId: "sgxwL8V39Lc", title: "0+0", artist: "한로로 HANRORO" },
    { youtubeId: "nbhdUqGemuU", title: "LET ME OUT", artist: "박혜원HYNN" },
    { youtubeId: "BY4sHNaV4WU", title: "눈의 꽃", artist: "박효신 PARK HYO SHIN" },
    { youtubeId: "jUMZ9IeoJtU", title: "Just Love Me", artist: "경서" },
    { youtubeId: "IUs-EPKtQJM", title: "Loved you so dearly in winter (코 끝이 찡하게)", artist: "차가을ChaGaEul" },
    { youtubeId: "CSSYv4qsgSc", title: "My Love (And)", artist: "BUZZ" },
    { youtubeId: "e5ayTYdwJsk", title: "The Eternal Moment", artist: "마크툽 MAKTUB Official" },
    { youtubeId: "ir-StgFSjmY", title: "Because You Don't Love Me", artist: "지아 ZIA Official" },
    { youtubeId: "qYJ3pxXEwdI", title: "사랑아", artist: "더 원 THE ONE" },
    { youtubeId: "z127C11tKsg", title: "If you lovingly call my name (다정히 내 이름을 부르면)", artist: "경서예지 GyeongseoYeji Channel" },
    { youtubeId: "0ujged1o7zg", title: "Memory Of The Wind", artist: "NAMMSE 나얼의 음악세계" },
    { youtubeId: "85rrbElFkTI", title: "남자를 몰라", artist: "BUZZ" },
    { youtubeId: "ULfAaYIuldI", title: "체념 (After Resignatoion / Retiment)", artist: "Big Mama" },
    { youtubeId: "4EQ_vqyojWU", title: "Late Night (늦은 밤 너의 집 앞 골목길에서)", artist: "노을Noel" },
    { youtubeId: "Ap0Z4J5MmLA", title: "중독된 사랑", artist: "Cho Jang Hyuck" },
    { youtubeId: "LP0lRsckX1A", title: "인사", artist: "BUMJIN" },
    { youtubeId: "YApzsfazibE", title: "Eternity (영원)", artist: "디셈버 DK" },
    { youtubeId: "ECg2aEGKQLI", title: "우리 왜 헤어져야 해", artist: "신예영 SIN YE YOUNG" },
    { youtubeId: "nD1p_H3qo_A", title: "HeeJae (희재)", artist: "성시경 SUNG SI KYUNG" },
    { youtubeId: "8x_gqPb7mmE", title: "Goodbye (잘가요)", artist: "주호" },
    { youtubeId: "TyCYGCCD6iQ", title: "Rhapsody of Sadness", artist: "임재현 Official" },
    { youtubeId: "q0Bc1lmn5fA", title: "One Love", artist: "M.C the MAX Official" },
    { youtubeId: "DWzWnonBZ2w", title: "Even if I close my eyes(2026)", artist: "지환(순순희)" },
    { youtubeId: "7Zs7UM-EBLs", title: "사랑합니다...", artist: "Tim" },
    { youtubeId: "6fc-X0T-H7I", title: "Happy Me (행복한 나를)", artist: "Big Mama" },
    { youtubeId: "iNRoCGpEwww", title: "Last Love", artist: "Tei" },
    { youtubeId: "XxOLNRjGg1A", title: "Rain and You", artist: "Rumble Fish" },
    { youtubeId: "JQyJD9o2WQE", title: "흰눈", artist: "Eru" },
    { youtubeId: "7WwPxz-BAe8", title: "Haeyo (2022) (해요 (2022))", artist: "#안녕_OFFICIAL" },
    { youtubeId: "MA79-uBPiSY", title: "내 눈물 모아 With My Tears", artist: "휘인 Whee In" },
    { youtubeId: "IhKjZk5AYRg", title: "Popcorn", artist: "도경수(DOH KYUNG SOO)" },
    { youtubeId: "YwRWIin3I6U", title: "I Still Love You (추억은 만남보다 이별에 남아)", artist: "Jung Dong Ha" },
    { youtubeId: "ioV6ejEaiq4", title: "Bad Love (차가워진 이 바람엔 우리가 써있어(Bad Love))", artist: "박혜원HYNN" },
    { youtubeId: "gqdQy6pyCy4", title: "I LOVE YOU", artist: "Position" },
    { youtubeId: "wxljxMJ3o1M", title: "FOREVER (2024)", artist: "전건호" },
    { youtubeId: "MPfr7QXZ9L8", title: "Heaven", artist: "Kim Hyun Sung" },
    { youtubeId: "BDqUNyV7UmU", title: "The Lonely Bloom Stands Alone (시든 꽃에 물을 주듯)", artist: "박혜원HYNN" },
    { youtubeId: "1mZEQl8q3w4", title: "Goodbye, My Summer", artist: "한로로 HANRORO" },
    { youtubeId: "gdj6a0hv0Uk", title: "벌써 일년", artist: "Brown Eyes" },
    { youtubeId: "wR24uFCaQ84", title: "without me", artist: "주호" },
    { youtubeId: "nuAiFzEkFZM", title: "여전히 아름다운지", artist: "Toy" },
    { youtubeId: "Klis6a-tLZw", title: "이제는 어떻게 사랑을 하나요", artist: "전건호" },
    { youtubeId: "MWHtUeY3y34", title: "Drinking Alone", artist: "Sung Tae (POSTMEN)" },
    { youtubeId: "qqoHyTAFIPs", title: "Timeless", artist: "SG Wannabe" },
    { youtubeId: "veUTBoY53yU", title: "물론 (With you)", artist: "Huh Gak" },
    { youtubeId: "HaycAOvfjHM", title: "Glowing Light (가장 찬란한 빛으로 쏟아지는)", artist: "박혜원HYNN" },
    { youtubeId: "NSCdxHtfjkk", title: "I Miss You So Much (미치게 그리워서)", artist: "지아 ZIA Official" },
    { youtubeId: "vbbDQvXXGBw", title: "Dial Your Number", artist: "#안녕_OFFICIAL" },
    { youtubeId: "7ATP7h-pB2I", title: "Never Ending Story", artist: "F." },
    { youtubeId: "slUTl_CtMR0", title: "Destiny (2025) (운명 (2025))", artist: "먼데이 키즈 Monday Kiz" },
    { youtubeId: "ckJlE2G4LQ4", title: "Heart (심(心))", artist: "디셈버 DK" },
    { youtubeId: "-s-J4UjtxDs", title: "낙원 (feat. 이재훈)", artist: "officialpsy" },
    { youtubeId: "UtYBunDqp30", title: "예술이야 (It's Art)", artist: "officialpsy" },
    { youtubeId: "iT267zwmFBw", title: "어땠을까 (What Would Have Been) ft. 박정현", artist: "officialpsy" },
    { youtubeId: "FL6bPjhzzqI", title: "I will be waiting (기다릴게)", artist: "Ha Dong Qn" },
    { youtubeId: "nwksfZMJXXs", title: "No Words Can Say", artist: "로이킴 Roy Kim" },
    { youtubeId: "oDlLNTwInBM", title: "감사", artist: "김동률 KIM DONG RYUL" },
    { youtubeId: "YBR7-BYsnXA", title: "그대 없는 밤에 (feat. 전상근)", artist: "H:CODE" },
    { youtubeId: "NGznnPbpZa4", title: "Goodbye", artist: "박효신 PARK HYO SHIN" },
    { youtubeId: "XAKL4SR2geQ", title: "I Miss You", artist: "SOYOU" },
    { youtubeId: "23paJQqts6Y", title: "How can i live without you (어떻게 내가 널 잊고 살아)", artist: "주호" },
    { youtubeId: "z40LVKReyp8", title: "Actually.. I miss you (Male Ver.) (사실 나는 (남자 Ver.))", artist: "전건호" },
    { youtubeId: "RxWfKHqNU-0", title: "기억을 걷는 시간 cover", artist: "김결" },
    { youtubeId: "ZIBoYP1MIt8", title: "Three days after", artist: "박혜원HYNN" },
    { youtubeId: "uBBz6H3B7F0", title: "A Person Closer to Tears (2026)", artist: "먼데이 키즈 Monday Kiz" },
    { youtubeId: "aQYnSloXrtA", title: "Just Watching You", artist: "Release" },
    { youtubeId: "Daj54FQNbG8", title: "It's love (사랑인걸)", artist: "Mose" },
    { youtubeId: "WpfWKRpWD6g", title: "Farewell Once Again (한번 더 이별)", artist: "성시경 SUNG SI KYUNG" },
  ] satisfies PlaylistTrack[],
};

export function youtubeWatchUrl(id: string): string {
  return `https://www.youtube.com/watch?v=${id}`;
}

export function youtubeThumb(id: string): string {
  return `https://i.ytimg.com/vi/${id}/hqdefault.jpg`;
}

/** 16:9 crop without hqdefault letterbox bars */
export function youtubeThumbFill(id: string): string {
  return `https://i.ytimg.com/vi/${id}/mqdefault.jpg`;
}
