export type SaveQuestLang = "ko" | "en";

export const SAVEQUEST_COPY = {
  ko: {
    navOverview: "개요",
    navFocus: "초점",
    navPipeline: "파이프라인",
    navSystem: "시스템",
    navProduct: "제품",
    navOutcome: "결과",
    summarize: "요약",
    sum1: "SaveQuest는 절약을 일일 퀘스트로 바꿉니다. 카드 결제 내역을 가맹점별로 읽고, 한도 도전과제를 만든 뒤 안전·위험·실패로 보여 줍니다.",
    sum2: "성공하면 XP와 코인을 받고, 줄인 금액은 랭킹에 올라갑니다. 코인으로는 캐릭터·펫·배경을 삽니다.",
    sum3: "학생 설문에서 74.2%가 절약의 중요성을 알면서도 실천하지 못했다고 답했습니다. 부족한 건 정보가 아니라 동기입니다.",
    intro: "절약이 필요한 건 아는데, 동기가 없어서 멈춥니다. SaveQuest는 결제 내역으로 도전과제를 만들고, 오늘 쓴 돈을 퀘스트 진행으로 보여 줍니다. 보상과 캐릭터가 다음 날을 다시 열게 합니다.",
    tagFe: "프론트엔드",
    tagFeTip: "홈 피드, 도전과제, 랭킹, 쇼핑 UI를 구현했습니다.",
    tagPipe: "결제 파이프라인",
    tagPipeTip: "카드 결제 → 가맹점 매칭 → 한도 판정 → 상태·보상.",
    tagSys: "챌린지 엔진",
    tagSysTip: "선택한 가맹점 한도에 가까워질수록 초록·주황·빨강으로 바뀝니다.",
    tagAi: "게이미피케이션",
    tagAiTip: "일일 도전, XP·코인, 레벨, 캐릭터 상점이 한 앱에 있습니다.",
    tagGold: "학생 타겟",
    tagGoldTip: "재미있는 걸 좋아하고 절약이 필요한 학생, 동기가 부족한 사람.",
    focus: "초점",
    focus1: "어려운 건 가계부를 보여주는 일이 아닙니다. 오늘 쓴 돈을 실패가 아니라 퀘스트로 읽히게 만드는 일입니다.",
    focus2: "핵심 질문: 결제를 어떻게 하면 끝까지 하는 하루 도전으로 바꿀 수 있을까?",
    focus3: "네 가지에 집중했습니다.",
    f1t: "결제가 퀘스트가 되게",
    f1d: "편의점 4,000원 이하처럼 가맹점과 한도를 고릅니다. 오늘 쓴 금액이 진행 바가 됩니다.",
    f2t: "안전 · 위험 · 실패",
    f2d: "한도에 가까워질수록 초록, 주황, 빨강. 위험일 때 알림이 가서 끊을 기회를 줍니다.",
    f3t: "한곳에서 머물게",
    f3d: "홈, 챌린지, 쇼핑, 내 정보가 같은 앱에 있습니다. 가계부 앱과 보상 앱을 오가지 않습니다.",
    f4t: "매일 돌아가는 보상",
    f4d: "성공하면 XP와 코인. 줄인 금액은 랭킹에 쌓입니다. 다음 날 퀘스트가 다시 열립니다.",
    scope: "범위",
    scopeP: "앱 화면과 챌린지 흐름을 맡았습니다. 결제 내역 분석과 보상 규칙은 한 파이프라인으로 맞춰, UI가 빈 숫자가 아니게 했습니다.",
    s1t: "화면",
    s1: ["홈 요약과 일일 도전", "챌린지와 랭킹", "캐릭터 상점", "알림과 설정"],
    s2t: "파이프라인",
    s2: ["카드 결제 수집", "가맹점 매칭", "한도 대비 사용액", "상태·보상 발행"],
    s3t: "규칙",
    s3: ["일일·기간 한도", "안전 / 위험 / 실패", "XP와 코인", "패널티"],
    s4t: "상점",
    s4: ["캐릭터", "펫", "배경", "랜덤박스"],
    pipe: "결제 파이프라인",
    pipe1: "결제가 들어오면 가맹점을 고르고, 한도와 비교한 뒤 상태를 붙입니다. 보상은 그 다음입니다.",
    pipe2: "다이어그램은 영어입니다. Collect, Match, Judge, Reward. 노드를 누르면 펼쳐집니다.",
    system: "시스템",
    sys1: "클라이언트는 홈·챌린지·쇼핑·프로필입니다. 서버는 결제 수집, 챌린지 판정, 보상·상점, 랭킹을 맡습니다.",
    sys2: "결제 원본과 유저 상태는 나눕니다. 모델이나 외부 카드 API는 가장자리에 두고, 매 화면 한가운데에 두지 않았습니다.",
    product: "제품",
    p1l: "홈",
    p1: "이번 달 아낀 금액과 레벨이 위에 있습니다. 아래는 오늘 도전과제입니다. 쓴 금액과 목표 금액이 바로 보입니다.",
    p2l: "챌린지 · 랭킹",
    p2: "한 달 평균 소비를 줄이는 미션과 순위를 같이 봅니다. 줄인 금액이 랭킹 단위입니다.",
    p3l: "쇼핑",
    p3: "모은 코인으로 캐릭터를 삽니다. 레벨과 꾸미기가 다음 도전을 열 이유가 됩니다.",
    demoHint: "홈, 챌린지, 상점이 한 앱에서 이어집니다.",
    outcome: "결과",
    outP: "절약을 정보 앱이 아니라 매일 켜는 퀘스트로 만들었습니다.",
    o1m: "74%",
    o1l: "실천 공백",
    o1d: "학생 설문에서 74.2%가 중요성은 알면서 실천하지 못했습니다.",
    o2m: "3",
    o2l: "상태",
    o2d: "안전, 위험, 실패. 한도에 가까워질수록 색이 바뀝니다.",
    o3m: "4",
    o3l: "화면이 한 앱에",
    o3d: "홈, 챌린지, 쇼핑, 내 정보가 도구를 나누지 않습니다.",
    o4m: "FE",
    o4l: "프론트엔드",
    o4d: "화면을 맡았고, 결제·보상 규칙이 UI 뒤에 실제 숫자로 있게 했습니다.",
  },
  en: {
    navOverview: "Overview",
    navFocus: "Focus",
    navPipeline: "Pipeline",
    navSystem: "System",
    navProduct: "Product",
    navOutcome: "Outcome",
    summarize: "Summarize",
    sum1: "SaveQuest turns saving into a daily quest. Card payments are read by merchant, turned into spend-limit challenges, then shown as safe, danger, or fail.",
    sum2: "Hit the limit and you get XP and coins. Money you did not spend goes on a ranking. Coins buy characters, pets, and backgrounds.",
    sum3: "In a student survey, 74.2% said they knew saving mattered and still did not do it. The missing piece is motivation, not information.",
    intro: "People know they should save. They stop because nothing pulls them back tomorrow. SaveQuest turns payment history into challenges and shows today’s spend as a quest bar. Rewards and characters are why the app opens again.",
    tagFe: "Frontend",
    tagFeTip: "Built the home feed, challenges, ranking, and shop UI.",
    tagPipe: "Payment pipeline",
    tagPipeTip: "Card charge → merchant match → limit check → status and reward.",
    tagSys: "Challenge engine",
    tagSysTip: "As spend nears the chosen merchant cap, the bar goes green, orange, then red.",
    tagAi: "Gamification",
    tagAiTip: "Daily quests, XP and coins, levels, and a character shop live in one app.",
    tagGold: "Student target",
    tagGoldTip: "Students who like games and need to save, and anyone short on motivation.",
    focus: "Focus",
    focus1: "The hard part is not a ledger. It is making today’s spend read as a quest instead of a failure.",
    focus2: "The core question: how do you take a payment and turn it into a daily challenge someone finishes?",
    focus3: "I focused on four things:",
    f1t: "Payments become quests",
    f1d: "Pick a merchant and a cap — under ₩4,000 at a convenience store. Today’s spend is the progress bar.",
    f2t: "Safe · danger · fail",
    f2d: "Green, orange, red as you near the cap. A warning fires on danger so there is still time to stop.",
    f3t: "One place to stay",
    f3d: "Home, challenge, shop, and profile live in the same app. No bounce between a ledger and a reward app.",
    f4t: "A reward that can run daily",
    f4d: "Success pays XP and coins. Money saved stacks on a ranking. Tomorrow’s quest opens again.",
    scope: "Scope",
    scopeP: "I owned the app surface and the challenge flow. Payment analysis and reward rules were wired as one pipeline so the UI was not empty numbers.",
    s1t: "Interface",
    s1: ["Home summary and daily quests", "Challenges and ranking", "Character shop", "Alerts and settings"],
    s2t: "Pipeline",
    s2: ["Card payment ingest", "Merchant match", "Spend vs cap", "Status and reward"],
    s3t: "Rules",
    s3: ["Daily and period caps", "Safe / danger / fail", "XP and coins", "Penalties"],
    s4t: "Shop",
    s4: ["Characters", "Pets", "Backgrounds", "Random boxes"],
    pipe: "Payment pipeline",
    pipe1: "A charge comes in, the merchant is matched, the cap is checked, then a status is attached. The reward is last.",
    pipe2: "The diagram stays in English. Collect, Match, Judge, Reward. Click a node to expand.",
    system: "System",
    sys1: "Clients are home, challenge, shop, and profile. The server owns payment ingest, challenge judgment, rewards and shop, and ranking.",
    sys2: "Raw payments and user state are split. Card APIs sit at the edge of the graph, not in the middle of every screen.",
    product: "Product",
    p1l: "Home",
    p1: "This month’s savings and level sit on top. Daily challenges sit below. Spend versus target is visible without extra taps.",
    p2l: "Challenge · ranking",
    p2: "A month-long “cut your average spend” mission sits next to a leaderboard. The unit is money you did not spend.",
    p3l: "Shop",
    p3: "Coins buy characters. Level and cosmetics are the reason the next challenge is worth opening.",
    demoHint: "Home, challenge, and shop run in one app.",
    outcome: "Outcome",
    outP: "Saving shipped as a daily quest, not an information app.",
    o1m: "74%",
    o1l: "Action gap",
    o1d: "74.2% of surveyed students knew saving mattered and still did not do it.",
    o2m: "3",
    o2l: "States",
    o2d: "Safe, danger, fail. Color shifts as spend nears the cap.",
    o3m: "4",
    o3l: "Surfaces in one app",
    o3d: "Home, challenge, shop, and profile sit together instead of splitting across tools.",
    o4m: "FE",
    o4l: "Frontend",
    o4d: "I owned the interface and kept payment and reward rules as real numbers behind the UI.",
  },
} as const;
