export type ScholubLang = "ko" | "en";

export const SCHOLUB_COPY = {
  ko: {
    navOverview: "개요",
    navFocus: "초점",
    navPipeline: "파이프라인",
    navSystem: "시스템",
    navProduct: "제품",
    navOutcome: "결과",
    summarize: "요약",
    sum1: "Scholub은 매일 쏟아지는 AI 논문을 실제로 읽을 수 있는 뉴스로 바꿉니다. arXiv에서 논문을 모으고, 학회 리뷰어 기준으로 걸러낸 뒤 요약·번역·태그·썸네일을 붙여 피드에 올립니다.",
    sum2: "프론트엔드를 맡았고, NestJS API·파이썬 크롤러·FastAPI LLM 서버까지 팀과 함께 구조를 잡았습니다. 추천, AI 검색, 토론 커뮤니티도 같은 제품 안에 있습니다.",
    sum3: "디지털 콘텐츠 개발 대회 생활 부문 금상을 받았습니다. 사람들이 만지는 건 화면이고, 매일 피드가 살아 있게 하는 건 파이프라인입니다.",
    intro: "매일 arXiv에 AI 논문이 수백 건씩 올라옵니다. 대부분은 제목에서 멈춥니다. Scholub은 그 논문을 크롤링하고, 리뷰어처럼 걸러낸 뒤 짧은 뉴스로 다시 씁니다. 검색, 추천, 토론까지 한곳에 있습니다.",
    tagFe: "프론트엔드",
    tagFeTip: "논문 피드, 읽기 화면, AI 검색, 토론 UI를 React로 설계하고 구현했습니다.",
    tagPipe: "논문 파이프라인",
    tagPipeTip: "arXiv 수집부터 피드 노출까지: 수집, 선별, 가공, 발행.",
    tagSys: "시스템 설계",
    tagSysTip: "NestJS, 크롤러, FastAPI LLM 서버를 팀과 맞춰 UI가 빈 목업이 아니게 했습니다.",
    tagAi: "AI 검색 · 추천",
    tagAiTip: "추천은 읽은 기록을 따릅니다. 검색과 요약은 별도 LLM 서버가 담당합니다.",
    tagGold: "금상",
    tagGoldTip: "디지털 콘텐츠 개발 대회 생활 부문 금상.",
    focus: "초점",
    focus1: "어려운 건 논문 목록을 보여주는 일이 아닙니다. 어떤 논문이 자리에 오를지 정하고, PDF가 아니라 뉴스처럼 읽히게 만드는 일입니다.",
    focus2: "핵심 질문: arXiv 덤프를 어떻게 하면 끝까지 읽는 하루 피드로 바꿀 수 있을까?",
    focus3: "네 가지에 집중했습니다.",
    f1t: "먼저 읽히게",
    f1d: "PDF보다 요약, 번역, 태그가 먼저입니다. 해당 분야를 모르는 사람도 읽기 화면에서 버틸 수 있어야 합니다.",
    f2t: "리뷰어 수준의 선별",
    f2d: "OpenAI가 학회 가이드라인으로 점수를 매깁니다. 피드가 “오늘 들어온 것”이 되지 않게 합니다.",
    f3t: "한곳에서 머물게",
    f3d: "피드, AI 검색, 추천, 토론이 같은 제품에 있습니다. 탭 다섯 개로 나가지 않습니다.",
    f4t: "매일 돌아가는 파이프라인",
    f4d: "수집, 선별, 가공, 저장, 노출. 한 단계라도 일회성 스크립트면 다음 날 피드는 죽습니다.",
    scope: "범위",
    scopeP: "프론트엔드와 제품 화면을 맡았습니다. 크롤러, NestJS API, LLM 서버는 팀과 같이 짜서 UI가 빈 엔드포인트 위 목업이 아니게 했습니다.",
    s1t: "화면",
    s1: ["논문 피드와 읽기 화면", "AI 검색", "토론 커뮤니티", "프로필과 선호"],
    s2t: "파이프라인",
    s2: ["arXiv 수집과 PDF 추출", "리뷰어 선별", "요약, 번역, 태그", "썸네일 생성"],
    s3t: "백엔드",
    s3: ["NestJS + Prisma + CQRS", "JWT 인증과 알림", "선호 기반 랭킹", "S3 자산, Redis 캐시"],
    s4t: "모델",
    s4: ["리뷰어 점수: OpenAI", "검색·요약: Perplexity", "썸네일: Gemini", "심층 분석: FastAPI 서브 에이전트"],
    pipe: "논문 파이프라인",
    pipe1: "원래는 여덟 칸이 한 줄로 이어져 있었습니다. 정확하지만 한눈에 안 들어옵니다. 루트 하나, 가지 몇 개, 자세한 건 펼쳤을 때만 보이게 묶었습니다.",
    pipe2: "다이어그램은 영어입니다. Collect, Filter, Enrich, Publish. 노드를 누르면 펼쳐집니다.",
    system: "시스템",
    sys1: "클라이언트는 서버 두 대와 이야기합니다. NestJS API는 유저, 논문, 토론, 알림을 맡습니다. FastAPI LLM 서버는 검색, 요약, 더 깊은 패스를 위한 서브 에이전트를 맡습니다.",
    sys2: "메타데이터는 Postgres, PDF와 썸네일은 S3, 세션은 Redis입니다. 모델은 그래프 가장자리에 두고, 매 요청 한가운데에 두지 않았습니다.",
    product: "제품",
    p1l: "홈 피드",
    p1: "선별된 논문이 카드로 올라옵니다. 인기 논문, 최신 연구, 추천이 한 화면에 있습니다. 알림은 관심 논문의 반박·후속 논문을 바로 띄웁니다.",
    p2l: "논문 상세 · AI 채팅",
    p2: "초록과 요약을 읽고, 문장을 채팅으로 보내 물을 수 있습니다. AI 뷰어와 원문 보기가 나란히 있습니다. 검색도 키워드 인덱스가 아니라 LLM 서버로 갑니다.",
    p3l: "프로필",
    p3: "반응한 논문과 토론한 논문이 갈립니다. 피드는 매일 바뀌고, 댓글과 반응이 사람을 붙입니다.",
    outcome: "결과",
    outP: "프론트 데모가 아니라 풀스택으로 나갔습니다.",
    o1m: "금상",
    o1l: "디지털 콘텐츠 대회",
    o1d: "디지털 콘텐츠 개발 대회 생활 부문 금상.",
    o2m: "1",
    o2l: "하루 논문 경로",
    o2d: "수집부터 피드까지 한 파이프라인입니다. 새 논문은 수동 발행 없이 올라갑니다.",
    o3m: "3",
    o3l: "화면이 한 앱에",
    o3d: "피드, AI 검색, 토론이 도구를 나누지 않고 같이 있습니다.",
    o4m: "FE",
    o4l: "프론트엔드",
    o4d: "화면을 맡았고, 팀과 구조를 맞춰 UI 뒤에 실제 데이터가 있게 했습니다.",
  },
  en: {
    navOverview: "Overview",
    navFocus: "Focus",
    navPipeline: "Pipeline",
    navSystem: "System",
    navProduct: "Product",
    navOutcome: "Outcome",
    summarize: "Summarize",
    sum1: "Scholub turns the daily flood of AI papers into news you can actually read. Papers come from arXiv, get screened against conference-style reviewer criteria, then rewritten with a summary, translation, tags, and a thumbnail before they hit the feed.",
    sum2: "I led the frontend and helped shape the system: a NestJS API, a Python crawler, and a FastAPI LLM server. Recommendations, AI search, and a discussion community live in the same product.",
    sum3: "It won gold in the Digital Content Development Competition (daily-life category). People touch the interface; the pipeline is what keeps the feed alive every day.",
    intro: "Hundreds of new AI papers land on arXiv every day. Most people never get past the title. Scholub crawls those papers, screens them like a reviewer, and republishes the ones that matter as short news — with search, recommendations, and a place to discuss them.",
    tagFe: "Frontend",
    tagFeTip: "Designed and built the paper feed, reading view, AI search, and discussion UI in React.",
    tagPipe: "Paper pipeline",
    tagPipeTip: "From arXiv crawl to feed: collect, filter, enrich, publish.",
    tagSys: "System design",
    tagSysTip: "Aligned NestJS, the crawler, and the FastAPI LLM server with the team so the UI was not a mock on empty endpoints.",
    tagAi: "AI search & recommend",
    tagAiTip: "Recommendations follow reading history. Search and summaries run on a dedicated LLM server.",
    tagGold: "Gold award",
    tagGoldTip: "Gold award, Digital Content Development Competition, daily-life category.",
    focus: "Focus",
    focus1: "The hard part is not showing a list of papers. It is deciding which ones deserve a slot, then making those papers feel like news instead of PDFs.",
    focus2: "The core question: how do you take an arXiv dump and turn it into a daily feed someone actually finishes?",
    focus3: "I focused on four things:",
    f1t: "Readable first",
    f1d: "Summary, translation, and tags before the PDF. The reading view should work for someone who is not already in the field.",
    f2t: "Reviewer-grade filter",
    f2d: "OpenAI scores each paper against conference-style guidelines so the feed is not just “whatever arrived today.”",
    f3t: "One place to stay",
    f3d: "Feed, AI search, recommendations, and discussion live in the same product. No bounce out to five tabs.",
    f4t: "A pipeline that can run daily",
    f4d: "Collect, filter, enrich, store, expose. If any step is a one-off script, the feed dies the next morning.",
    scope: "Scope",
    scopeP: "I owned the frontend and the product surface. The crawler, NestJS API, and LLM server were designed with the team so the UI was not a mock on empty endpoints.",
    s1t: "Interface",
    s1: ["Paper feed and reading view", "AI search", "Discussion community", "Profiles and preferences"],
    s2t: "Pipeline",
    s2: ["arXiv crawl and PDF extract", "Reviewer screening", "Summary, translation, tags", "Thumbnail generation"],
    s3t: "Backend",
    s3: ["NestJS + Prisma + CQRS", "JWT auth and notifications", "Preference-based ranking", "S3 assets, Redis cache"],
    s4t: "Models",
    s4: ["Reviewer scoring: OpenAI", "Search & summary: Perplexity", "Thumbnails: Gemini", "Deeper analysis: FastAPI sub-agent"],
    pipe: "Paper pipeline",
    pipe1: "The original flow was eight boxes in a line. Accurate, hard to scan. I grouped it as one root, a few branches, details only when you open them.",
    pipe2: "The diagram stays in English. Collect, Filter, Enrich, Publish. Click a node to expand.",
    system: "System",
    sys1: "Clients talk to two servers. The NestJS API owns users, papers, discussions, and notifications. The FastAPI LLM server owns search, summarization, and a sub-agent for deeper passes.",
    sys2: "Postgres holds metadata. S3 holds PDFs and thumbnails. Redis caches sessions. Models sit at the edge of the graph, not in the middle of every request.",
    product: "Product",
    p1l: "Home feed",
    p1: "Screened papers land as cards. Popular, latest, and recommended sit on one screen. Notifications surface rebuttals and follow-ups on papers you already care about.",
    p2l: "Paper detail · AI chat",
    p2: "Read the abstract and summary, then send a sentence to chat. AI viewer and original sit side by side. Search goes to the LLM server, not a keyword index.",
    p3l: "Profile",
    p3: "Papers you reacted to and papers you discussed are split. The feed changes daily; comments and reactions are why people stay.",
    outcome: "Outcome",
    outP: "It shipped as a full stack, not a frontend demo.",
    o1m: "Gold",
    o1l: "Digital Content award",
    o1d: "Gold in the daily-life category of the Digital Content Development Competition.",
    o2m: "1",
    o2l: "Daily paper path",
    o2d: "Crawl to feed is one pipeline. New papers land without a manual publish step.",
    o3m: "3",
    o3l: "Surfaces in one app",
    o3d: "Feed, AI search, and discussion sit together instead of splitting across tools.",
    o4m: "FE",
    o4l: "Frontend",
    o4d: "I owned the interface and worked through the architecture with the team so the UI had real data behind it.",
  },
} as const;
