export type SipsiilbanLang = "ko" | "en";

export const SIPSIILBAN_COPY = {
  ko: {
    navOverview: "개요",
    navFocus: "초점",
    navFlow: "흐름",
    navProduct: "제품",
    summarize: "요약",
    sum1: "십시일반은 근처 편의점·프랜차이즈를 지도에서 찾아 QR로 결제하는 React Native 앱입니다. 로그인부터 신원 인증, 매장 탐색, 결제, 주문 확인까지 한 흐름으로 이어집니다.",
    sum2: "프론트엔드/메인 개발로 화면 흐름을 설계하고 구현했습니다. 모바일 앱, FastAPI 백엔드, 가맹점용 POS까지 세 갈래입니다. 제11회 선린 해커톤 은상입니다.",
    sum3: "질문은 하나입니다. 인증과 결제를 여러 앱으로 쪼개지 않고, 가맹점 앞에서 바로 끝낼 수 있는가.",
    intro: "편의점과 프랜차이즈 앞에서 앱을 여러 개 열지 않습니다. 십시일반은 신원을 확인하고, 근처 가맹점을 지도에서 고른 뒤, QR 한 장으로 결제합니다.",
    tagFe: "프론트엔드",
    tagFeTip: "로그인부터 QR 결제까지 화면 흐름을 설계하고 React Native로 구현했습니다.",
    tagApp: "React Native",
    tagAppTip: "Expo 앱. 지도, 카메라/이미지 피커, QR 생성 화면을 직접 만들었습니다.",
    tagQr: "QR 결제",
    tagQrTip: "가맹점 앞에서 쓰는 QR. 만료 시간과 주문 상태가 같은 앱에 있습니다.",
    tagSilver: "은상",
    tagSilverTip: "제11회 선린 해커톤 은상.",
    focus: "초점",
    focus1: "어려운 건 QR을 그리는 일이 아닙니다. 인증, 매장, 결제, 주문을 한 상태 머신으로 끊기지 않게 잇는 일입니다.",
    focus2: "핵심 질문: 가맹점 앞에 선 사람이, 다른 앱으로 나가지 않고 결제를 끝낼 수 있는가.",
    focus3: "네 가지에 집중했습니다.",
    f1t: "인증이 먼저",
    f1d: "소득·직업 증명을 올리고 사진을 확인하기 전에는 결제가 열리지 않습니다. 혜택을 받는 사람이 맞는지가 출발점입니다.",
    f2t: "근처에서 고름",
    f2d: "홈에서 자주 가는 가맹점을 보고, 지도와 검색으로 나머지를 찾습니다. 카테고리와 거리가 먼저입니다.",
    f3t: "QR이 곧 결제",
    f3d: "금액을 고르면 QR이 생기고 만료 시간이 돌아갑니다. 가맹점 POS가 읽으면 주문이 이어집니다.",
    f4t: "목으로 먼저 검증",
    f4d: "백엔드 연동 전에 화면 전환과 상태를 목 데이터로 맞춰 두었습니다. 연동이 들어와도 흐름이 바뀌지 않게 했습니다.",
    flow: "흐름",
    flow1: "앱 흐름은 선린톤에서 짠 그대로입니다. 로그인 다음이 온보딩과 서류 인증이고, 그다음이 홈·지도·검색, 마지막이 QR과 주문 상태입니다.",
    flow2: "아래 화면은 그 순서입니다. 화살표로 넘기면 인증부터 결제까지 이어집니다.",
    fl1t: "로그인 · 온보딩",
    fl1d: "구글 로그인 후 서비스 혜택을 위해 신원 인증을 안내합니다.",
    fl2t: "서류 인증",
    fl2d: "소득·직업 증명을 찍고, 제대로 찍혔는지 확인한 뒤에야 넘어갑니다.",
    fl3t: "홈 · 지도 · 검색",
    fl3d: "잔액과 자주 가는 가맹점, 지도 핀, 추천 검색이 한 앱에 있습니다.",
    fl4t: "QR · 주문",
    fl4d: "QR을 보여주고 만료를 셉니다. 주문이 잡히면 상태 화면으로 갑니다.",
    scope: "범위",
    scopeP: "화면 흐름과 모바일 앱을 맡았습니다. 결제 API와 가맹점 POS는 팀과 맞춰, UI가 빈 목업이 아니게 했습니다.",
    s1t: "앱",
    s1: ["구글 로그인", "온보딩 · 서류 업로드", "홈 · 지도 · 검색", "QR 결제 · 주문 상태"],
    s2t: "POS",
    s2: ["QR 수신", "주문 처리", "가맹점 온보딩"],
    s3t: "백엔드",
    s3: ["FastAPI", "인증 · 가맹점", "QR 결제 API"],
    s4t: "스택",
    s4: ["React Native · Expo", "TypeScript", "NestJS · FastAPI", "Next.js POS"],
    product: "제품",
    p1l: "홈",
    p1: "QR 결제 버튼, 사용 가능 금액, 카테고리, 자주 가는 가맹점이 한 화면에 있습니다. 결제로 가는 가장 짧은 길입니다.",
    p2l: "지도 · 검색",
    p2: "지도에서 가맹점 핀을 보고, 검색에서 최근 검색어와 추천 매장을 고릅니다. 위치와 카테고리가 목록을 자릅니다.",
    p3l: "QR 결제",
    p3: "현장 결제 QR과 만료 시간이 가운데에 있습니다. 가맹점이 읽으면 주문이 시작되고, 조리·완료 상태가 같은 앱에 남습니다.",
  },
  en: {
    navOverview: "Overview",
    navFocus: "Focus",
    navFlow: "Flow",
    navProduct: "Product",
    summarize: "Summarize",
    sum1: "Sipsiilban is a React Native app for finding nearby convenience stores and franchises on a map and paying with QR. Login, ID verification, store search, payment, and order status sit in one flow.",
    sum2: "I was frontend/main developer: screen flow, then implementation. Mobile app, FastAPI backend, and a merchant POS. Silver at the 11th Sunrin Hackathon.",
    sum3: "One question: can someone finish auth and payment at the counter without bouncing through other apps.",
    intro: "You should not open three apps at a convenience store. Sipsiilban verifies who you are, lets you pick a nearby merchant on a map, and pays with one QR.",
    tagFe: "Frontend",
    tagFeTip: "Designed and built the screen flow from login to QR payment in React Native.",
    tagApp: "React Native",
    tagAppTip: "Expo app. I built the map, camera/image picker, and QR screens.",
    tagQr: "QR payment",
    tagQrTip: "A QR you show at the counter. Expiry and order status live in the same app.",
    tagSilver: "Silver",
    tagSilverTip: "Silver, 11th Sunrin Hackathon.",
    focus: "Focus",
    focus1: "The hard part is not drawing a QR. It is keeping auth, store, payment, and order in one state machine that does not break.",
    focus2: "The core question: can someone at the counter finish payment without leaving for another app.",
    focus3: "I focused on four things.",
    f1t: "Auth first",
    f1d: "Payment stays closed until income and job proof are uploaded and the photo is confirmed. Who gets the benefit is the start.",
    f2t: "Pick nearby",
    f2d: "Home shows frequent merchants. Map and search cover the rest. Category and distance come first.",
    f3t: "QR is the payment",
    f3d: "Pick an amount, get a QR, watch the timer. When the POS reads it, the order continues.",
    f4t: "Mock the flow first",
    f4d: "Screen transitions and state were wired on mocks before the backend. Integration did not rewrite the flow.",
    flow: "Flow",
    flow1: "The app follows the Sunrin hackathon path. Login, then onboarding and document verify, then home / map / search, then QR and order status.",
    flow2: "The screens below are in that order. Flip through to go from verify to pay.",
    fl1t: "Login · onboarding",
    fl1d: "Google login, then an identity check so benefits can open.",
    fl2t: "Document verify",
    fl2d: "Shoot income/job proof, confirm the photo, then continue.",
    fl3t: "Home · map · search",
    fl3d: "Balance, frequent stores, map pins, and recommended search in one app.",
    fl4t: "QR · order",
    fl4d: "Show a QR and count down. Once an order lands, the status screen takes over.",
    scope: "Scope",
    scopeP: "I owned the screen flow and the mobile app. Payment APIs and merchant POS were aligned with the team so the UI was not a mock on empty endpoints.",
    s1t: "App",
    s1: ["Google login", "Onboarding · document upload", "Home · map · search", "QR pay · order status"],
    s2t: "POS",
    s2: ["QR receive", "Order handling", "Merchant onboarding"],
    s3t: "Backend",
    s3: ["FastAPI", "Auth · merchants", "QR payment API"],
    s4t: "Stack",
    s4: ["React Native · Expo", "TypeScript", "NestJS · FastAPI", "Next.js POS"],
    product: "Product",
    p1l: "Home",
    p1: "QR pay, available balance, categories, and frequent merchants on one screen. The shortest path to payment.",
    p2l: "Map · search",
    p2: "Pins on the map, recent queries and recommended stores in search. Location and category cut the list.",
    p3l: "QR payment",
    p3: "An in-person QR and an expiry timer in the center. When the merchant reads it, the order starts and status stays in the same app.",
  },
} as const;
