export type SlopLang = "ko" | "en";

export const SLOP_COPY = {
  ko: {
    navOverview: "개요",
    navFocus: "초점",
    navPipeline: "파이프라인",
    navSystem: "시스템",
    navProduct: "제품",
    summarize: "요약",
    sum1: "SLOP은 웹에서 읽던 글을 그 자리에서 숏폼으로 바꿉니다. 크롬 확장이 페이지를 파싱하고, 서버가 요약·쇼츠를 만들면 세로 영상을 바로 재생합니다.",
    sum2: "확장은 Plasmo, 웹은 Next.js, API는 NestJS입니다. 확장과 웹 프론트를 설계하고 구현했습니다. 제12회 선린 해커톤 금상입니다.",
    sum3: "질문은 하나입니다. 긴 기사를 끝까지 읽지 못하는 사람이, 그 페이지를 떠나지 않고 쇼츠를 볼 수 있는가.",
    intro: "긴 뉴스는 제목에서 끝납니다. SLOP은 그 글을 페이지 위에서 숏폼으로 바꿉니다. 플로팅 버튼을 누르면 분석·요약·영상 생성이 이어지고, 완성되면 세로 쇼츠를 바로 봅니다.",
    tagFe: "프론트엔드",
    tagFeTip: "Plasmo 확장과 Next.js 웹앱을 설계하고 구현했습니다.",
    tagExt: "크롬 확장",
    tagExtTip: "페이지 파싱, 플로팅 버튼, 텍스트 선택, 인라인 재해석, 쇼츠 패널.",
    tagPipe: "쇼츠 파이프라인",
    tagPipeTip: "페이지 파싱 → 요약 → 쇼츠 생성 → 피드 재생.",
    tagGold: "금상",
    tagGoldTip: "제12회 선린 해커톤 금상.",
    focus: "초점",
    focus1: "어려운 건 영상을 만드는 일이 아닙니다. 읽고 있던 페이지를 떠나지 않고, 그 글이 쇼츠가 되게 하는 일입니다.",
    focus2: "핵심 질문: 기사를 끝까지 못 읽는 사람이, 같은 탭에서 숏폼을 볼 수 있는가.",
    focus3: "네 가지에 집중했습니다.",
    f1t: "페이지를 안 떠남",
    f1d: "읽던 기사 위에서 버튼을 누르면 바로 파싱이 시작됩니다. 확장 창을 열고 URL을 붙이는 순간, 읽던 맥락은 이미 끊깁니다.",
    f2t: "본문만 집기",
    f2d: "같은 기사라도 사이트마다 본문 위치가 다릅니다. 광고·관련기사·깨진 인코딩을 빼고 넘겨야 쇼츠가 다른 글을 요약하지 않습니다.",
    f3t: "기다림이 비지 않게",
    f3d: "분석, 요약, 영상까지 단계가 보입니다. 끝나면 새 탭이 아니라, 그 패널에서 세로 쇼츠가 바로 재생됩니다.",
    f4t: "취향이 피드가 됨",
    f4d: "말투와 관심 분야를 온보딩에서 한 번 고릅니다. 이후 릴스는 그 설정으로 쌓이고, 좋아요와 댓글도 같은 웹앱에 남습니다.",
    scope: "범위",
    scopeP: "크롬 확장과 Next.js 웹 프론트를 맡았습니다. 쇼츠 생성과 인증은 NestJS API에 맡기고, UI가 빈 목업이 아니게 맞췄습니다.",
    s1t: "확장",
    s1: ["플로팅 버튼", "페이지 파싱", "텍스트 선택 팝업", "인라인 재해석"],
    s2t: "웹",
    s2: ["구글 OAuth 로그인", "온보딩", "릴스 피드", "검색과 프로필"],
    s3t: "백엔드",
    s3: ["NestJS + Prisma", "쇼츠 생성·추천", "파일·S3", "Meilisearch"],
    s4t: "모델",
    s4: ["OpenRouter", "요약·스크립트", "진행 상태 회신", "피드 추천"],
    pipe: "쇼츠 파이프라인",
    pipe1: "글을 잡고, 요약하고, 영상을 만들고, 피드에 올립니다. 확장이 수집을 열고, 서버가 생성을 닫습니다.",
    pipe2: "다이어그램은 영어입니다. Parse, Generate, Publish. 노드를 누르면 펼쳐집니다.",
    system: "시스템",
    sys1: "클라이언트는 둘입니다. 확장은 기사 위에서 파싱하고 생성을 요청합니다. 웹은 로그인, 온보딩, 릴스, 검색을 맡습니다.",
    sys2: "NestJS가 인증·쇼츠·파일을 맡고, Prisma·S3·Redis·Meilisearch·OpenRouter가 가장자리에 있습니다.",
    product: "제품",
    p1l: "확장",
    p1: "플로팅 버튼을 누르면 사이트 분석부터 쇼츠까지 진행이 보입니다. 특정 뉴스에서는 원문 옆에 쉬운 문장이 붙습니다.",
    p2l: "온보딩",
    p2: "말투, 표시 형식, 쇼츠 스타일, 관심 분야, 용어 난이도를 저장합니다. 이후 피드는 그 설정을 따릅니다.",
    p3l: "릴스",
    p3: "완성된 세로 영상을 틱톡처럼 스크롤합니다. 좋아요, 댓글, 검색, 프로필이 같은 웹앱에 있습니다.",
  },
  en: {
    navOverview: "Overview",
    navFocus: "Focus",
    navPipeline: "Pipeline",
    navSystem: "System",
    navProduct: "Product",
    summarize: "Summarize",
    sum1: "SLOP turns the article you are already reading into a short-form video on that page. A Chrome extension parses the page; the server summarizes and builds a vertical short you can play immediately.",
    sum2: "The extension is Plasmo, the web app is Next.js, the API is NestJS. I designed and built the extension and the web frontend. It won gold at the 12th Sunrin Hackathon.",
    sum3: "One question: can someone who never finishes a long article get a consumable short without leaving the tab.",
    intro: "Long news dies at the title. SLOP turns that copy into a short on the same page. Tap the floating button, watch parse → summary → render, then play the vertical video.",
    tagFe: "Frontend",
    tagFeTip: "Designed and built the Plasmo extension and the Next.js web app.",
    tagExt: "Chrome extension",
    tagExtTip: "Page parse, floating button, text selection, inline rewrite, shorts panel.",
    tagPipe: "Shorts pipeline",
    tagPipeTip: "Parse the page → summarize → generate a short → play it in the feed.",
    tagGold: "Gold award",
    tagGoldTip: "Gold, 12th Sunrin Hackathon.",
    focus: "Focus",
    focus1: "The hard part is not making a video. It is making the article already on screen become a short, without leaving the page.",
    focus2: "The core question: can someone who never finishes a long article get a consumable short in the same tab.",
    focus3: "I focused on four things:",
    f1t: "Stay on the page",
    f1d: "Tap the button on the article and parsing starts there. Opening the extension to paste a URL already breaks the reading context.",
    f2t: "Grab the body only",
    f2d: "The same article lives in a different DOM on every site. Ads, related stories, and broken encoding have to come off, or the short summarizes the wrong text.",
    f3t: "Waiting is not a blank",
    f3d: "Parse, summary, and render show as steps. When it is done, the vertical short plays in that panel — not in a new tab.",
    f4t: "Taste becomes the feed",
    f4d: "Tone and topics are chosen once in onboarding. The reels stack from those settings, and likes and comments stay in the same web app.",
    scope: "Scope",
    scopeP: "I owned the Chrome extension and the Next.js frontend. Shorts generation and auth sit on the NestJS API, wired so the UI is not a mock.",
    s1t: "Extension",
    s1: ["Floating button", "Page parse", "Text-select popup", "Inline rewrite"],
    s2t: "Web",
    s2: ["Google OAuth", "Onboarding", "Reels feed", "Search and profile"],
    s3t: "Backend",
    s3: ["NestJS + Prisma", "Shorts generate and rank", "Files and S3", "Meilisearch"],
    s4t: "Models",
    s4: ["OpenRouter", "Summary and script", "Progress callbacks", "Feed ranking"],
    pipe: "Shorts pipeline",
    pipe1: "Catch the article, summarize it, render a video, put it on a feed. The extension opens collection; the server closes generation.",
    pipe2: "The diagram stays in English. Parse, Generate, Publish. Click a node to expand.",
    system: "System",
    sys1: "Two clients. The extension parses on the article and asks for a short. The web app owns login, onboarding, reels, and search.",
    sys2: "NestJS owns auth, shorts, and files. Prisma, S3, Redis, Meilisearch, and OpenRouter sit at the edge.",
    product: "Product",
    p1l: "Extension",
    p1: "The floating button shows parse through render. On some news sites, a simpler sentence sits next to the original paragraph.",
    p2l: "Onboarding",
    p2: "Tone, format, shorts style, topics, and term difficulty are stored. The feed follows those settings.",
    p3l: "Reels",
    p3: "Finished vertical videos scroll like TikTok. Likes, comments, search, and profile live in the same web app.",
  },
} as const;
